### PR TITLE
better UI args

### PR DESCRIPTION
**Pull request by jeremywrnr**

### CODE REVIEW

**Comment by ethanjohnson89** [comment]
Just saw this PR - as I mentioned over in Messenger, I already pushed a fix for this directly to "dev" (which passes Travis) before you posted this.

Your approach is somewhat cleaner, and you also addressed a few other things in the PR, so we should probably merge it instead of going with what I wrote - hopefully this won't cause a nasty merge conflict.

To fix the workspace tests (which are erroring out in Travis for the pull request), I added .split(" ") to the artificially-constructed command lines being issued, to convert them into argv arrays.

**Comment by jeremywrnr** [comment]
Dang, just checked messenger. Ok, yea it says there are some merge conflicts, so I'll take care of them and make sure the branch i merge in passes.

**Comment by jeremywrnr** [comment]
Just rebased off of dev, and handled all the merging. Should be good now.

**Comment by ethanjohnson89** [comment]
Cool, looks good. Yeah, sorry for the confusion on that. I saw you had assigned it to me on Asana, so I assumed nobody else was working on it.

**Pull request merged**
